// ═══════════════════════════════════════════════════════════
//  cards.js — TCG Card Database
// ═══════════════════════════════════════════════════════════
//  Rarities : Common · Rare · Epic · Mythical · Legendary · SSSR · Hidden
//  Classes  : Skibidi · Gigachad · BabyOil · NPC · Rizzlord · Yapper
//             Aura · Delulu · Crashout · LetHimCook · Sus · NegativeAura
//
//  ID ranges (base cards):
//    Common    1  – 200      Rare      201 – 400
//    Epic      401 – 600     Mythical  601 – 750
//    Legendary 751 – 900     SSSR      901 – 1000
//    Hidden    1001 – 1050   (code-unlock only, pullWeight: 0)
//
//  Shiny IDs are generated automatically: shinyId = baseId + 5000
//  DO NOT add shiny entries manually — just add base cards below.
//
//  Pull weight ranges:
//    Common    400 – 800   sell   2 – 10
//    Rare      120 – 250   sell  20 – 60
//    Epic       30 – 70    sell 100 – 250
//    Mythical    6 – 15    sell 500 – 1200
//    Legendary   1 – 4     sell 2500 – 5000
//    SSSR     0.05 – 0.8   sell 7500 – 25000
// ═══════════════════════════════════════════════════════════

// Shiny is ~400× rarer than the base card. Adjust here to change for all cards.
const SHINY_WEIGHT_MULTIPLIER = 0.0025;

// ── BASE CARDS ─────────────────────────────────────────────
// Shinies are auto-generated at the bottom — only edit this array.

const _BASE_CARDS = [

  // ──────────── COMMON ─────────────────────────────────────
  // id 1 – 200
  {
    id: 1,
    name: "Christoph",
    rarity: "Common",
    class: "Skibidi",
    description: "A normal day in math class...",
    pullWeight: 800,
    imageUrl: "assets/cards/common/1.png",
    sellValue: 2,
    isShiny: false,
    baseId: 1,
    type: "fighter",
    hp: 80,
    attackDamage: 15,
    effect: null,
  },
  {
    id: 2,
    name: "Batman Ali",
    rarity: "Common",
    class: "Skibidi",
    description: "A DARK hero from a different dimension. Fights crime with his trusty belt.",
    pullWeight: 750,
    imageUrl: "assets/cards/common/2.png",
    sellValue: 3,
    isShiny: false,
    baseId: 2,
    type: "fighter",
    hp: 90,
    attackDamage: 20,
    effect: null,
  },
  {
    id: 3,
    name: "Enes mit P",
    rarity: "Common",
    class: "NPC",
    description: "Mert Enes zeig mir deinen Pe...",
    pullWeight: 700,
    imageUrl: "assets/cards/common/3.png",
    sellValue: 4,
    isShiny: false,
    baseId: 3,
    type: "fighter",
    hp: 100,
    attackDamage: 15,
    effect: null,
  },
  {
    id: 4,
    name: "Alexander",
    rarity: "Common",
    class: "BabyOil",
    description: "Owner of an untamable garden gnome.",
    pullWeight: 650,
    imageUrl: "assets/cards/common/4.png",
    sellValue: 5,
    isShiny: false,
    baseId: 4,
    type: "fighter",
    hp: 130,
    attackDamage: 30,
    effect: null,
  },
  {
    id: 5,
    name: "Ammarius",
    rarity: "Common",
    class: "Skibidi",
    description: "A mysterious figure with a hidden past.",
    pullWeight: 600,
    imageUrl: "assets/cards/common/5.png",
    sellValue: 6,
    isShiny: false,
    baseId: 5,
    type: "fighter",
    hp: 95,
    attackDamage: 27,
    effect: null,
  },
  {
    id: 6,
    name: "Johannissimus",
    rarity: "Common",
    class: "LetHimCook",
    description: "He is just here... doesn't do much, but he's here.",
    pullWeight: 550,
    imageUrl: "assets/cards/common/6.png",
    sellValue: 7,
    isShiny: false,
    baseId: 6,
    type: "fighter",
    hp: 82,
    attackDamage: 16,
    effect: null,
  },
  {
    id: 7,
    name: "Toilette Amo",
    rarity: "Common",
    class: "Sus",
    description: "Ohhh you dont wanna know what he does in the bathroom...",
    pullWeight: 500,
    imageUrl: "assets/cards/common/7.png",
    sellValue: 8,
    isShiny: false,
    baseId: 7,
    type: "fighter",
    hp: 80,
    attackDamage: 20,
    effect: null,
  },
  {
    id: 8,
    name: "Pablo",
    rarity: "Common",
    class: "Legend",
    description: "Just Pablo. Ali's Uncle.",
    pullWeight: 450,
    imageUrl: "assets/cards/common/8.jpg",
    sellValue: 9,
    isShiny: false,
    baseId: 8,
    type: "fighter",
    hp: 96,
    attackDamage: 29,
    effect: null,
  },
  {
    id: 9,
    name: "casual Amostaner",
    rarity: "Common",
    class: "Yapper",
    description: "Let him enjoy his food or he will get uneasy.",
    pullWeight: 400,
    imageUrl: "assets/cards/common/9.png",
    sellValue: 10,
    isShiny: false,
    baseId: 9,
    type: "fighter",
    hp: 85,
    attackDamage: 19,
    effect: null,
  },
  {
    id: 10,
    name: "Monseur Luca",
    rarity: "Common",
    class: "Aura",
    description: "He belongs to the Monseur-Mafia. But he is chill.      Buff: Reduces incoming damage by 2.5%.",
    pullWeight: 350,
    imageUrl: "assets/cards/common/10.png",
    sellValue: 11,
    isShiny: false,
    baseId: 10,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {damageReduction: 0.025},
  },
  {
    id: 11,
    name: "Monseur Ali",
    rarity: "Common",
    class: "Sus",
    description: "He belongs to the Monseur-Mafia. He is not chill at all.",
    pullWeight: 350,
    imageUrl: "assets/cards/common/11.png",
    sellValue: 11,
    isShiny: false,
    baseId: 11,
    type: "fighter",
    hp: 135,
    attackDamage: 35,
    effect: null,
  },
  {
    id: 12,
    name: "Pink Monseur Ali",
    rarity: "Common",
    class: "Gigachad",
    description: "Monseur Ali's rare pink variant. He is very chill.      Buff: Reduces incoming damage by 5%.",
    pullWeight: 420,
    imageUrl: "assets/cards/common/12.png",
    sellValue: 9,
    isShiny: false,
    baseId: 12,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {damageReduction: 0.05},
  },
  {
    id: 13,
    name: "Free mini men",
    rarity: "Common",
    class: "",
    description: "He did nothing... #FreeMiniMen",
    pullWeight: 600,
    imageUrl: "assets/cards/common/13.png",
    sellValue: 5,
    isShiny: false,
    baseId: 13,
    type: "fighter",
    hp: 80,
    attackDamage: 10,
    effect: null,
  },
  {
    id: 14,
    name: "Sussy Baka Alex",
    rarity: "Common",
    class: "Sus",
    description: "He has something in his pocket... but you dont wanna know what.",
    pullWeight: 500,
    imageUrl: "assets/cards/common/14.png",
    sellValue: 7,
    isShiny: false,
    baseId: 14,
    type: "fighter",
    hp: 60,
    attackDamage: 60,
    effect: null,
  },
  {
    id: 15,
    name: "A & C",
    rarity: "Common",
    class: "NegativeAura",
    description: "Idk.. math class was really that boring.     Buff: Heals 5% of damage recieved as HP.",
    pullWeight: 400,
    imageUrl: "assets/cards/common/15.png",
    sellValue: 10,
    isShiny: false,
    baseId: 15,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {lifeSteal: 0.05},
  },
  {
    id: 16,
    name: "Baran the Döner King",
    rarity: "Common",
    class: "Legend",
    description: "He may not be the smartest, but his Döners are to die for.",
    pullWeight: 300,
    imageUrl: "assets/cards/common/16.png",
    sellValue: 12,
    isShiny: false,
    baseId: 16,
    type: "fighter",
    hp: 140,
    attackDamage: 35,
    effect: null,
  },
  {
    id: 17,
    name: "Biking Ali",
    rarity: "Common",
    class: "Yapper",
    description: "He bikes a lot, but yapps even more on his vlogs.",
    pullWeight: 400,
    imageUrl: "assets/cards/common/17.png",
    sellValue: 10,
    isShiny: false,
    baseId: 17,
    type: "fighter",
    hp: 120,
    attackDamage: 30,
    effect: null,
  },

  // ──────────── RARE ───────────────────────────────────────
  // id 201 – 400
  {
    id: 201,
    name: "Kitty Alex",
    rarity: "Rare",
    class: "Rizzlord",
    description: "If cute was a person.",
    pullWeight: 250,
    imageUrl: "assets/cards/rare/1.png",
    sellValue: 20,
    isShiny: false,
    baseId: 201,
    type: "fighter",
    hp: 115,
    attackDamage: 25,
    effect: null,
  },
  {
    id: 202,
    name: "locked in Amostaner",
    rarity: "Rare",
    class: "LetHimCook",
    description: "Do not intterupt him.",
    pullWeight: 240,
    imageUrl: "assets/cards/rare/2.png",
    sellValue: 25,
    isShiny: false,
    baseId: 202,
    type: "fighter",
    hp: 120,
    attackDamage: 42,
    effect: null,
  },
  {
    id: 203,
    name: "Mysterious Figure",
    rarity: "Rare",
    class: "Legend",
    description: "Who is he? Noone knows.",
    pullWeight: 230,
    imageUrl: "assets/cards/rare/3.png",
    sellValue: 30,
    isShiny: false,
    baseId: 203,
    type: "fighter",
    hp: 160,
    attackDamage: 50,
    effect: null,
  },
  {
    id: 204,
    name: "They got mini men",
    rarity: "Rare",
    class: "NegativeAura",
    description: "On a biking trip they caught mini men and put them in a cage.",
    pullWeight: 220,
    imageUrl: "assets/cards/rare/4.png",
    sellValue: 35,
    isShiny: false,
    baseId: 204,
    type: "fighter",
    hp: 140,
    attackDamage: 35,
    effect: null,
  },
  {
    id: 205,
    name: "Monseur Ali in da Toilet",
    rarity: "Rare",
    class: "Sus",
    description: "We dont know what he is doing in there, but it cant be good. After all, he is Monseur Ali.",
    pullWeight: 210,
    imageUrl: "assets/cards/rare/5.png",
    sellValue: 40,
    isShiny: false,
    baseId: 205,
    type: "fighter",
    hp: 145,
    attackDamage: 45,
    effect: null,
  },
  {
    id: 206,
    name: "Hungry Enes",
    rarity: "Rare",
    class: "Sus",
    description: "He is always hungry. But not for food...     Buff: Increases attack damage by 2.5%.",
    pullWeight: 200,
    imageUrl: "assets/cards/rare/6.png",
    sellValue: 45,
    isShiny: false,
    baseId: 206,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {attackBoost: 1.025},
  },
  {
    id: 207,
    name: "Monseur Essbar",
    rarity: "Rare",
    class: "Aura",
    description: "He belongs to the Monseur-Mafia. He is the lead of the supply chain. Do not mess with him.",
    pullWeight: 190,
    imageUrl: "assets/cards/rare/7.png",
    sellValue: 50,
    isShiny: false,
    baseId: 207,
    type: "buff",
    hp: 200,
    attackDamage: 80,
    effect: null,
  },
  {
    id: 208,
    name: "Monseur Amo",
    rarity: "Rare",
    class: "Legend",
    description: "He belongs to the Monseur-Mafia. He is the one who operates in the shadows. And he is mini mens brother",
    pullWeight: 180,
    imageUrl: "assets/cards/rare/8.png",
    sellValue: 55,
    isShiny: false,
    baseId: 208,
    type: "fighter",
    hp: 205,
    attackDamage: 60,
    effect: null,
  },
  {
    id: 209,
    name: "Rali",
    rarity: "Rare",
    class: "LetHimCook",
    description: "He is Alis brother. And the former head of the Monseur-Mafias Raiding Division. Be carefull, he is a heavy hitter.",
    pullWeight: 170,
    imageUrl: "assets/cards/rare/9.png",
    sellValue: 60,
    isShiny: false,
    baseId: 209,
    type: "fighter",
    hp: 140,
    attackDamage: 100,
    effect: null,
  },
  {
    id: 210,
    name: "Freaky Amostaner",
    rarity: "Rare",
    class: "Sus",
    description:
        "... idk man at least he got the Strawhats.",
    pullWeight: 160,
    imageUrl: "assets/cards/rare/10.png",
    sellValue: 60,
    isShiny: false,
    baseId: 210,
    type: "fighter",
    hp: 200,
    attackDamage: 20,
    effect: null,
  },
  {
    id: 211,
    name: "Myserrious Biker and Amo",
    rarity: "Rare",
    class: "Aura",
    description:
        "We dont know who he is, maybe someone from the Monseur-Mafia.",
    pullWeight: 150,
    imageUrl: "assets/cards/rare/11.png",
    sellValue: 70,
    isShiny: false,
    baseId: 211,
    type: "fighter",
    hp: 180,
    attackDamage: 60,
    effect: null,
  },
  {
    id: 212,
    name: "Apfeltaschen Pirat wanted poster",
    rarity: "Rare",
    class: "Aura",
    description:
        "Legends say that the Apfeltaschen Pirat is still out there, sailing the seven seas in search of the perfect Apfeltasche.      Buff: Increases critical hit chance by 10%.",
    pullWeight: 140,
    imageUrl: "assets/cards/rare/12.png",
    sellValue: 80,
    isShiny: false,
    baseId: 212,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {increasedCritic: 0.1},
  },
  {
    id: 213,
    name: "Monseur Bleached Buzzcut",
    rarity: "Rare",
    class: "Aura",
    description: "He has a bleached buzzcut and is known for his aggressive fighting style. Only few can handle his intensity in battle.",
    pullWeight: 130,
    imageUrl: "assets/cards/rare/13.png",
    sellValue: 85,
    isShiny: false,
    baseId: 213,
    type: "fighter",
    hp: 220,
    attackDamage: 120,
    effect: null,
  },
  {
    id: 214,
    name: "Samu & Federico",
    rarity: "Rare",
    class: "LetHimCook",
    description: "They are a duo of begging fine shyts... but well we dont talk about the success rate.",
    pullWeight: 120,
    imageUrl: "assets/cards/rare/14.png",
    sellValue: 90,
    isShiny: false,
    baseId: 214,
    type: "fighter",
    hp: 200,
    attackDamage: 90,
    effect: null,
  },

  // ──────────── EPIC ───────────────────────────────────────
  // id 401 – 600
  {
    id: 401,
    name: "CJ on 1 HP",
    rarity: "Epic",
    class: "Rizzlord",
    description: "Even his own shadow fears him.",
    pullWeight: 70,
    imageUrl: "assets/cards/epic/1.png",
    sellValue: 100,
    isShiny: false,
    baseId: 401,
    type: "fighter",
    hp: 90,
    attackDamage: 80,
    effect: null,
  },
  {
    id: 402,
    name: "The three musketeers",
    rarity: "Epic",
    class: "Aura",
    description:
        "On a journey..",
    pullWeight: 65,
    imageUrl: "assets/cards/epic/2.png",
    sellValue: 120,
    isShiny: false,
    baseId: 402,
    type: "fighter",
    hp: 300,
    attackDamage: 90,
    effect: null,
  },
  {
    id: 403,
    name: "Halal Ali",
    rarity: "Epic",
    class: "Rizzlord",
    description:
        "Be carefull, he is very halal. He might bless you... or smite you.",
    pullWeight: 60,
    imageUrl: "assets/cards/epic/3.png",
    sellValue: 140,
    isShiny: false,
    baseId: 403,
    type: "fighter",
    hp: 250,
    attackDamage: 110,
    effect: null,
  },
  {
    id: 404,
    name: "Luca caught in da Toilet",
    rarity: "Epic",
    class: "NegativeAura",
    description:
        "What was he doing in there... we will never know. But it cant be good.",
    pullWeight: 55,
    imageUrl: "assets/cards/epic/4.png",
    sellValue: 160,
    isShiny: false,
    baseId: 404,
    type: "fighter",
    hp: 120,
    attackDamage: 80,
    effect: null,
  },
  {
    id: 405,
    name: "Amos chocolate side",
    rarity: "Epic",
    class: "Rizzlord",
    description:
        "He is as sweet as chocolate, but as dangerous as a blackhole.",
    pullWeight: 50,
    imageUrl: "assets/cards/epic/5.png",
    sellValue: 180,
    isShiny: false,
    baseId: 405,
    type: "fighter",
    hp: 100,
    attackDamage: 180,
    effect: null,
  },
  {
    id: 406,
    name: "KingRali",
    rarity: "Epic",
    class: "Legend",
    description:
        "Be carefull, he is the king of the supply chain of the Monseur-Mafia.",
    pullWeight: 45,
    imageUrl: "assets/cards/epic/6.png",
    sellValue: 200,
    isShiny: false,
    baseId: 406,
    type: "fighter",
    hp: 200,
    attackDamage: 150,
    effect: null,
  },
  {
    id: 407,
    name: "Zoro Rali",
    rarity: "Epic",
    class: "Aura",
    description:
        "He will become the greatest swordsman in the world... or at least in the Monseur-Mafia.",
    pullWeight: 40,
    imageUrl: "assets/cards/epic/7.png",
    sellValue: 220,
    isShiny: false,
    baseId: 407,
    type: "fighter",
    hp: 250,
    attackDamage: 190,
    effect: null,
  },
  {
    id: 408,
    name: "Shy Rosa",
    rarity: "Epic",
    class: "Crashout",
    description:
        "If she sees you while you clip her... just run.",
    pullWeight: 35,
    imageUrl: "assets/cards/epic/8.png",
    sellValue: 240,
    isShiny: false,
    baseId: 408,
    type: "fighter",
    hp: 130,
    attackDamage: 200,
    effect: null,
  },
  {
    id: 409,
    name: "Crazy B",
    rarity: "Epic",
    class: "Delulu",
    description:
        "He is as unpredictable, the Monseur-Mafia calls him delulu, but as dangerous as a blackbear.",
    pullWeight: 30,
    imageUrl: "assets/cards/epic/9.png",
    sellValue: 260,
    isShiny: false,
    baseId: 409,
    type: "fighter",
    hp: 220,
    attackDamage: 210,
    effect: null,
  },

  // ──────────── MYTHICAL ───────────────────────────────────
  // id 601 – 750
  {
    id: 601,
    name: "Boxing Amo",
    rarity: "Mythical",
    class: "Aura",
    description: "Be carefull, he may knock you down.. or himself.",
    pullWeight: 15,
    imageUrl: "assets/cards/mythical/1.png",
    sellValue: 500,
    isShiny: false,
    baseId: 601,
    type: "fighter",
    hp: 200,
    attackDamage: 100,
    effect: null,
  },
  {
    id: 602,
    name: "Rizzy Amo",
    rarity: "Mythical",
    class: "Rizzlord",
    description:
        "He is as charming as a rizzlord, but fear him.",
    pullWeight: 14,
    imageUrl: "assets/cards/mythical/2.png",
    sellValue: 650,
    isShiny: false,
    baseId: 602,
    type: "fighter",
    hp: 250,
    attackDamage: 120,
    effect: null,
  },
  {
    id: 603,
    name: "Monseur Mafias Executives",
    rarity: "Mythical",
    class: "Legend",
    description:
        "The most powerful and influential members of the Monseur-Mafia.    Buff: Reflects 10% of incoming damage back to the attacker.",
    pullWeight: 13,
    imageUrl: "assets/cards/mythical/3.png",
    sellValue: 800,
    isShiny: false,
    baseId: 603,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {thorns: 0.1},
  },
  {
    id: 604,
    name: "Unicorn Rali",
    rarity: "Mythical",
    class: "Gigachad",
    description:
        "A mystical creature with the power to grant wishes or destroy futures.",
    pullWeight: 12,
    imageUrl: "assets/cards/mythical/4.png",
    sellValue: 900,
    isShiny: false,
    baseId: 604,
    type: "fighter",
    hp: 350,
    attackDamage: 200,
    effect: null,
  },
  {
    id: 605,
    name: "Food vlogger Amo",
    rarity: "Mythical",
    class: "Yapper",
    description:
        "In his off days he likes to vlog about food. But be carefull, he might get hangry and attack you with his camera.",
    pullWeight: 11,
    imageUrl: "assets/cards/mythical/5.png",
    sellValue: 1050,
    isShiny: false,
    baseId: 605,
    type: "fighter",
    hp: 200,
    attackDamage: 150,
    effect: null,
  },
  {
    id: 606,
    name: "A day of with da gang",
    rarity: "Mythical",
    class: "Gigachad",
    description:
        "Experience the thrill of a day with the gang1      Buff: Increases attack damage by 10% and reduces incoming damage by 10%",
    pullWeight: 10,
    imageUrl: "assets/cards/mythical/6.png",
    sellValue: 1200,
    isShiny: false,
    baseId: 606,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {attackBoost: 1.1, damageReduction: 0.1},
  },
  {
    id: 607,
    name: "How did we get here?",
    rarity: "Mythical",
    class: "Gigachad",
    description:
        "A mysterious card with an unknown origin. Even the garden gnom tries to hide.",
    pullWeight: 9,
    imageUrl: "assets/cards/mythical/7.png",
    sellValue: 1350,
    isShiny: false,
    baseId: 607,
    type: "fighter",
    hp: 300,
    attackDamage: 150,
    effect: null,
  },
  {
    id: 608,
    name: "Garden Gnom Stare",
    rarity: "Mythical",
    class: "Crashout",
    description:
        "Behold yourself in the unyielding gaze of the Garden Gnom... she has very few HP but her stare is deadly.",
    pullWeight: 8,
    imageUrl: "assets/cards/mythical/8.png",
    sellValue: 1500,
    isShiny: false,
    baseId: 608,
    type: "fighter",
    hp: 100,
    attackDamage: 280,
    effect: null,
  },

  // ──────────── LEGENDARY ──────────────────────────────────
  // id 751 – 900
  {
    id: 751,
    name: "Heracles & Hercules",
    rarity: "Legendary",
    class: "Gigachad",
    description: "One man.",
    pullWeight: 4,
    imageUrl: "assets/cards/legendary/1.png",
    sellValue: 2750,
    isShiny: false,
    baseId: 751,
    type: "fighter",
    hp: 350,
    attackDamage: 150,
    effect: null,
  },
  {
    id: 752,
    name: "Monesur Mafia vice boss",
    rarity: "Legendary",
    class: "Gigachad",
    description:
        "The second most powerful member of the Monseur-Mafia. He is known for his ruthless tactics and strategic mind.      Buff: Increases attack damage by 60% and increases critical hit chance by 30%",
    pullWeight: 1,
    imageUrl: "assets/cards/legendary/2.png",
    sellValue: 5500,
    isShiny: false,
    baseId: 752,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {attackBoost: 1.6, increasedCritic: 0.3},
  },
  {
    id: 753,
    name: "Monkey D. Meow",
    rarity: "Legendary",
    class: "LetHimCook",
    description:
        "He is going to be the King of the pirates... or at least the king of the cats.",
    pullWeight: 3.5,
    imageUrl: "assets/cards/legendary/3.png",
    sellValue: 3000,
    isShiny: false,
    baseId: 753,
    type: "fighter",
    hp: 300,
    attackDamage: 200,
    effect: null,
  },
  {
    id: 754,
    name: "Abu Lankabel",
    rarity: "Legendary",
    class: "Yapper",
    description:
        "He is the definition of ragebait and yapping nonsense",
    pullWeight: 3,
    imageUrl: "assets/cards/legendary/4.png",
    sellValue: 3500,
    isShiny: false,
    baseId: 754,
    type: "fighter",
    hp: 330,
    attackDamage: 80,
    effect: null,
  },
  {
    id: 755,
    name: "Christoph on 1 HP",
    rarity: "Legendary",
    class: "NPC",
    description:
        "He is on 1 HP, he just want to relax. Do not dare to disturb him at any cost.",
    pullWeight: 2.5,
    imageUrl: "assets/cards/legendary/5.png",
    sellValue: 4000,
    isShiny: false,
    baseId: 755,
    type: "fighter",
    hp: 100,
    attackDamage: 220,
    effect: null,
  },
  {
    id: 756,
    name: "Zesty Alex",
    rarity: "Legendary",
    class: "BabyOil",
    description:
        "He is onto something... hope it isnt you",
    pullWeight: 2,
    imageUrl: "assets/cards/legendary/6.png",
    sellValue: 4500,
    isShiny: false,
    baseId: 756,
    type: "fighter",
    hp: 250,
    attackDamage: 200,
    effect: null,
  },
  {
    id: 757,
    name: "Loked in garden gnome",
    rarity: "Legendary",
    class: "Delulu",
    description:
        "Never did I saw someone as locked in as her while eating...      Buff: increases Attack by 80%",
    pullWeight: 1.5,
    imageUrl: "assets/cards/legendary/7.png",
    sellValue: 5000,
    isShiny: false,
    baseId: 757,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect:{attackBoost: 1.8} ,
  },
  {
    id: 758,
    name: "Ali & Rose",
    rarity: "Legendary",
    class: "Delulu",
    description:
        "idk how I got there...",
    pullWeight: 1,
    imageUrl: "assets/cards/legendary/8.png",
    sellValue: 5500,
    isShiny: false,
    baseId: 758,
    type: "fighter",
    hp: 400,
    attackDamage: 140,
    effect: null,
  },
  {
    id: 759,
    name: "Ali & Rose pink edition",
    rarity: "Legendary",
    class: "Aura",
    description:
        "Lowkey thos tracks were fire...",
    pullWeight: 2,
    imageUrl: "assets/cards/legendary/9.png",
    sellValue: 4500,
    isShiny: false,
    baseId: 759,
    type: "fighter",
    hp: 400,
    attackDamage: 180,
    effect: null,
  },

  // ──────────── SSSR ───────────────────────────────────────
  // id 901 – 1000
  {
    id: 901,
    name: "mini men black edition",
    rarity: "SSSR",
    class: "BabyOil",
    description: "Be carefull with food around him, he might spawn behind you.",
    pullWeight: 0.8,
    imageUrl: "assets/cards/sssr/1.png",
    sellValue: 7500,
    isShiny: false,
    baseId: 901,
    type: "fighter",
    hp: 300,
    attackDamage: 130,
    effect: null,
  },
  {
    id: 902,
    name: "Alex Anders",
    rarity: "SSSR",
    class: "Rizzlord",
    description:
        "That boy gettin rizzyyyy",
    pullWeight: 0.7,
    imageUrl: "assets/cards/sssr/2.png",
    sellValue: 8250,
    isShiny: false,
    baseId: 902,
    type: "fighter",
    hp: 330,
    attackDamage: 190,
    effect: null,
  },
  {
    id: 903,
    name: "mini men vs big guy",
    rarity: "SSSR",
    class: "Crashout",
    description:
        "IceSpice bet on big guy",
    pullWeight: 0.6,
    imageUrl: "assets/cards/sssr/3.png",
    sellValue: 9000,
    isShiny: false,
    baseId: 903,
    type: "fighter",
    hp: 350,
    attackDamage: 220,
    effect: null,
  },
  {
    id: 904,
    name: "Jason Black Edition",
    rarity: "SSSR",
    class: "Aura",
    description:
        "Why does he look at us like we did it?",
    pullWeight: 0.5,
    imageUrl: "assets/cards/sssr/4.png",
    sellValue: 9750,
    isShiny: false,
    baseId: 904,
    type: "fighter",
    hp: 210,
    attackDamage: 280,
    effect: null,
  },
  {
    id: 905,
    name: "The Gang after Demon Slayer movie",
    rarity: "SSSR",
    class: "Legend",
    description:
        "Akazas backstory was peak as hell.     Buff: Heals 30% of the damage recieved",
    pullWeight: 0.6,
    imageUrl: "assets/cards/sssr/5.png",
    sellValue: 10500,
    isShiny: false,
    baseId: 905,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {lifeSteal: 0.3},
  },
  {
    id: 906,
    name: "Monseur Ali looksmaxxing",
    rarity: "SSSR",
    class: "Gigachad",
    description:
        "With messy middlepart and that look in his eyes... But do not let yourself get foold, he is the heavy hitter of the Monseur-Mafia. ",
    pullWeight: 0.5,
    imageUrl: "assets/cards/sssr/6.png",
    sellValue: 11250,
    isShiny: false,
    baseId: 906,
    type: "fighter",
    hp: 250,
    attackDamage: 300,
    effect: null,
  },
  {
    id: 907,
    name: "Arabasta Pose with da gang",
    rarity: "SSSR",
    class: "Legend",
    description:
        "What a legendary moment... Buff: Damage reduction by 65%",
    pullWeight: 0.4,
    imageUrl: "assets/cards/sssr/7.png",
    sellValue: 12000,
    isShiny: false,
    baseId: 907,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {damageReduction: 0.65},
  },
  {
    id: 908,
    name: "a Legendary Trio",
    rarity: "SSSR",
    class: "Legend",
    description:
        "The Trio that is undefeatable.",
    pullWeight: 0.3,
    imageUrl: "assets/cards/sssr/8.png",
    sellValue: 12750,
    isShiny: false,
    baseId: 908,
    type: "fighter",
    hp: 480,
    attackDamage: 330,
    effect: null,
  },

  // ──────────── HIDDEN ─────────────────────────────────────
  // id 1001 – 1050  —  code-unlock only, pullWeight always 0
  {
    id: 1001,
    name: "Rosa Abdullah",
    rarity: "Hidden",
    class: "Legend",
    description: "You'll never know.",
    pullWeight: 0,
    imageUrl: "assets/cards/hidden/1.png",
    sellValue: 65000,
    isShiny: false,
    baseId: 1001,
    type: "fighter",
    hp: 670,
    attackDamage: 187,
    effect: null,
  },
  {
    id: 1002,
    name: "Herr Billinger",
    rarity: "Hidden",
    class: "Gigachad",
    description: "He may be your greatest supporter or enemy.      Buff: Reduces incoming damage by 95%.",
    pullWeight: 0,
    imageUrl: "assets/cards/hidden/2.png",
    sellValue: 50000,
    isShiny: false,
    baseId: 1002,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {damageReduction: 0.95},
  },
  {
    id: 1003,
    name: "Ali's son",
    rarity: "Hidden",
    class: "Rizzlord",
    description: "Noone knows his name.        Buff: Increases attack damage by 95%.",
    pullWeight: 0,
    imageUrl: "assets/cards/hidden/3.png",
    sellValue: 55000,
    isShiny: false,
    baseId: 1003,
    type: "buff",
    hp: null,
    attackDamage: null,
    effect: {attackBoost: 1.95},
  },
  {
    id: 1004,
    name: "Doubble A",
    rarity: "Hidden",
    class: "NegativeAura",
    description:
        "Idk what we were thinking...",
    pullWeight: 0,
    imageUrl: "assets/cards/hidden/4.png",
    sellValue: 45000,
    isShiny: false,
    baseId: 1004,
    type: "fighter",
    hp: 200,
    attackDamage: 280,
    effect: null,
  },
  {
    id: 1005,
    name: "A random monday...",
    rarity: "Hidden",
    class: "Yapper",
    description:
        "On a rainy monday...",
    pullWeight: 0,
    imageUrl: "assets/cards/hidden",
    sellValue: 60000,
    isShiny: false,
    baseId: 1005,
    type: "fighter",
    hp: 300,
    attackDamage: 280,
    effect: null,
  },

];

// ── AUTO-SHINY GENERATION ─────────────────────────────────
// Generates a ✨ shiny for every base card above.
//   shinyId   = baseId + 5000
//   name      = name + " ✨"
//   desc      = description + " [Shiny]"
//   weight    = pullWeight × SHINY_WEIGHT_MULTIPLIER
//   sellValue = sellValue  × 50
// Everything else (hp, atk, effect, rarity, class…) is inherited as-is.

function _makeShiny(card) {
  return {
    ...card,
    id:          card.id + 5000,
    name:        card.name + " ✨",
    description: card.description + " [Shiny]",
    pullWeight:  card.pullWeight * SHINY_WEIGHT_MULTIPLIER,
    sellValue:   card.sellValue  * 50,
    isShiny:     true,
  };
}

const CARD_DATABASE = [
  ..._BASE_CARDS,
  ..._BASE_CARDS.map(_makeShiny),
];